"""empty message

Revision ID: 241488818e92
Revises: cbf5620f8e15
Create Date: 2017-09-05 21:27:30.084580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241488818e92'
down_revision = 'cbf5620f8e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('can_no_participation', sa.Boolean(), nullable=True),
    sa.Column('can_view_after_contest', sa.Boolean(), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamid', sa.Integer(), nullable=True),
    sa.Column('contestid', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('banned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contestid'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['teamid'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'awards', sa.Column('contestid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'awards', 'contests', ['contestid'], ['id'])
    op.add_column(u'challenges', sa.Column('contestid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'challenges', 'contests', ['contestid'], ['id'])
    op.add_column(u'solves', sa.Column('contestid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'solves', 'contests', ['contestid'], ['id'])
    op.add_column(u'teams', sa.Column('cas_name', sa.String(length=128), nullable=True))
    op.add_column(u'teams', sa.Column('full_name', sa.String(length=128), nullable=True))
    op.add_column(u'wrong_keys', sa.Column('contestid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wrong_keys', 'contests', ['contestid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wrong_keys', type_='foreignkey')
    op.drop_column(u'wrong_keys', 'contestid')
    op.drop_column(u'teams', 'full_name')
    op.drop_column(u'teams', 'cas_name')
    op.drop_constraint(None, 'solves', type_='foreignkey')
    op.drop_column(u'solves', 'contestid')
    op.drop_constraint(None, 'challenges', type_='foreignkey')
    op.drop_column(u'challenges', 'contestid')
    op.drop_constraint(None, 'awards', type_='foreignkey')
    op.drop_column(u'awards', 'contestid')
    op.drop_table('participations')
    op.drop_table('contests')
    # ### end Alembic commands ###
